defaults: &defaults
  working_directory: ~/ethstream
  docker:
    - image: circleci/node:8.9.4

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ethstream-{{ checksum "package.json" }}
            - v1-ethstream-
      - run: yarn install
      - save_cache:
          keys:
            - v1-ethstream-{{ checksum "package.json" }}
            - v1-ethstream-
      - run: yarn build

  test:
    <<: *defaults

    steps:
      - run: yarn test

  publish:
    <<: *defaults

    steps:
      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: echo "npm publish"

workflows:
  version: 2

  test:
    jobs:
      - build
      - test

  publish:
    jobs:
      - build
      - test
      - deploy
    tags:
      only: /v.*/
